# Configura\u00E7\u00F5es de Produ\u00E7\u00E3o
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logs
logging.level.root=INFO
logging.level.br.com.circulou=INFO
